import type { Job } from '@/lib/types';

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Femme de Ménage Expérimentée',
    category: 'housekeeper',
    location: 'Abidjan, Cocody',
    salary: 75000,
    salaryType: 'month',
    description: 'Recherche une femme de ménage méticuleuse et fiable pour un appartement de 150m². Tâches incluant nettoyage complet, repassage et gestion du linge. Expérience avec les surfaces délicates est un plus.',
    requirements: ['3+ ans d\'expérience', 'Références vérifiables', 'Autonome et pro-active', 'Français courant'],
    image: 'housekeeper-1',
  },
  {
    id: '2',
    title: 'Nanny Anglophone pour Deux Enfants',
    category: 'nanny',
    location: 'Abidjan, Riviera',
    salary: 150000,
    salaryType: 'month',
    description: 'Famille cherche une nanny anglophone pour s\'occuper de deux enfants (3 et 5 ans) à temps plein. Responsabilités : sorties d\'école, activités ludiques et éducatives, préparation des repas.',
    requirements: ['Anglais langue maternelle ou bilingue', 'Expérience avec les jeunes enfants', 'Certification premiers secours', 'Permis de conduire B'],
    image: 'nanny-1',
  },
  {
    id: '3',
    title: 'Chauffeur Privé pour Famille',
    category: 'driver',
    location: 'Abidjan, Marcory',
    salary: 180000,
    salaryType: 'month',
    description: 'Recherche chauffeur privé discret et professionnel pour assurer les déplacements d\'une famille. Conduite de véhicules de luxe. Flexibilité horaire requise.',
    requirements: ['5+ ans d\'expérience comme chauffeur privé', 'Casier judiciaire vierge', 'Excellente connaissance d\'Abidjan', 'Présentation impeccable'],
    image: 'driver-1',
  },
  {
    id: '4',
    title: 'Majordome / Butler pour Propriété',
    category: 'butler',
    location: 'Assinie',
    salary: 350000,
    salaryType: 'month',
    description: 'Gestion complète d\'une villa de luxe. Coordination du personnel, service à table, gestion des stocks, accueil des invités. Poste logé.',
    requirements: ['Expérience en hôtellerie de luxe ou comme majordome', 'Excellentes compétences en communication', 'Anglais et Français courants', 'Discrétion absolue'],
    image: 'butler-1',
  },
    {
    id: '5',
    title: 'Aide Ménagère à la journée',
    category: 'housekeeper',
    location: 'Yamoussoukro',
    salary: 5000,
    salaryType: 'day',
    description: 'Recherche une aide ménagère pour une journée complète de nettoyage. Grand ménage de printemps pour une villa.',
    requirements: ['Expérience souhaitée', 'Fiable et ponctuelle', 'Respect des consignes'],
    image: 'housekeeper-2',
  },
  {
    id: '6',
    title: 'Garde d\'enfants après l\'école',
    category: 'nanny',
    location: 'Bouaké',
    salary: 45000,
    salaryType: 'month',
    description: 'Recherche une personne de confiance pour récupérer un enfant de 8 ans à l\'école, l\'aider avec ses devoirs et l\'accompagner à ses activités.',
    requirements: ['Expérience avec les enfants', 'Patient(e) et pédagogue', 'Disponible de 16h30 à 19h en semaine'],
    image: 'nanny-2',
  }
];
