// This file is automatically generated. Do not modify it manually.
// To regenerate this file, need to remove this file and run the studio command again.
// For more information, please refer to the documentation: https://cloud.google.com/docs/gen-app-builder/recommendations-multimodal-agent-for-web#connect-to-firebase-backend

export const firebaseConfig = {
  "apiKey": "AIzaSyD7B4nhy5xHFK6sFW1X-0Jg-ub3f9QMkr8",
  "authDomain": "studio-8267913793-481fa.firebaseapp.com",
  "projectId": "studio-8267913793-481fa",
  "storageBucket": "studio-8267913793-481fa.appspot.com",
  "messagingSenderId": "859664539828",
  "appId": "1:859664539828:web:1e3f843d1a8c9b3a1a3b4c"
};
